version: 0.2

env:
  variables:
    TAG: latest

phases:
  install:
    commands:
      - echo "Logging into Amazon ECR"
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo "Build starting on $(date)"
      - echo "Building the container image"
      - docker build -t $REPOSITORY_URI:$TAG
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the container image"
      - docker push $REPOSITORY_URL:$TAG
      - echo "Writing image definitions file"
      - printf '[{"name":"web","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > imagedefinitions.json

# This file is used by CodeDeploy.
artifacts:
  files: imagedefinitions.json
