version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:rw
      - ./scripts:/opt/scripts
    environment:
      CLASSIFYR_DATABASE_HOST: "db"
      POSTGRES_PASSWORD: "${CLASSIFYR_DATABASE_PASSWORD:-thisisprobablyabadidea!}"
      POSTGRES_USER: "${CLASSIFYR_DATABASE_USERNAME:-classifyr}"
    command: /opt/scripts/initdb.sh
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/classifyr
    ports:
      - "3000:3000"
    depends_on:
      - db
